# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 665e8ce820a8b9a957a890027feb291e0ba76f898dcdb99492bf0b931989339d4f601c92369ecad657be1b6bdc55bf0b59b5ce7c0e221e128037a2e7f7bc126e

test:
  secret_key_base: ef8f990c39f792ccab11c6eb80a3e9517806246e38ddfcae1adbc3d1e804f4e2d99b3d2c69015e809392d2f479ddccc7d02ddc4479d8bdc9918b59ca637f2366

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
